/**
 * Content templates for rule-based generation
 */

export const fitnessTemplates = {
  topics: [
    "Importance of Morning Workouts",
    "Office Stretches",
    "Quick Lunch Break Exercises",
    "Post-Work Energy Boosters",
    "Weekend Recovery Routines",
    "Desk Ergonomics",
    "Mindful Movement",
    "Strength Training Basics",
    "Cardio for Busy Schedules",
    "Nutrition for Energy",
    "Sleep and Recovery",
    "Stress-Relief Exercises",
    "Home Workout Essentials",
    "Fitness Tracking",
    "Goal Setting Strategies",
    "Work-Life Balance",
    "Injury Prevention",
    "Mental Health Benefits",
    "Community Support",
    "Sustainable Habits",
    "Technology and Fitness",
    "Outdoor Activities",
    "Mind-Body Connection",
    "Progress Celebration",
    "Overcoming Plateaus",
    "Fitness Myths Debunked",
    "Time Management Tips",
    "Motivation Techniques",
    "Long-term Success",
    "Fitness Journey Reflection"
  ],
  
  captions: [
    "Starting your day with a workout boosts energy and productivity. Make it a habit!",
    "Don't let your desk kill your gains. Try these 3 moves every hour!",
    "Your lunch break is the perfect time for a quick energy boost. No excuses!",
    "Beat the afternoon slump with these post-work exercises that take just 10 minutes.",
    "Weekends are for recovery and preparation. Rest smart, train hard!",
    "Your desk setup affects your health more than you think. Time to optimize!",
    "Movement is medicine. Even 5 minutes of mindful exercise can change your day.",
    "Strength training isn't just for bodybuilders. Everyone needs it!",
    "Cardio doesn't have to be boring. Find what works for your schedule.",
    "What you eat directly impacts your energy levels. Fuel your body right!",
    "Sleep is your body's recovery time. Don't skip it!",
    "Stress is a killer. These exercises will help you manage it effectively.",
    "You don't need a gym to get fit. Your living room is your new workout space!",
    "Track your progress to stay motivated. Small wins add up to big results!",
    "Set SMART goals and watch your fitness journey transform.",
    "Balance is key. Work hard, play hard, rest well!",
    "Prevention is better than cure. Protect your body from injuries.",
    "Exercise is the best antidepressant. Your mental health matters!",
    "Find your tribe. Community support makes all the difference.",
    "Build habits that last. Sustainability over quick fixes!",
    "Use technology to your advantage. Apps can be your personal trainer.",
    "Nature is the best gym. Get outside and move!",
    "Your mind and body are connected. Train both for optimal results.",
    "Celebrate every milestone, no matter how small. Progress is progress!",
    "Plateaus are normal. Here's how to break through them.",
    "Don't believe everything you hear. Let's debunk common fitness myths.",
    "Time is your most valuable asset. Use it wisely for your health.",
    "Motivation comes and goes. Discipline is what keeps you going.",
    "Fitness is a marathon, not a sprint. Think long-term success.",
    "Reflect on your journey. How far have you come?"
  ],
  
  hashtags: [
    "#FitnessTips #MorningMotivation #HealthyLiving",
    "#DeskWorkout #HealthyLiving #WorkplaceWellness",
    "#LunchBreakWorkout #QuickExercise #NoExcuses",
    "#PostWorkEnergy #QuickWorkout #EnergyBoost",
    "#WeekendRecovery #RestDay #RecoveryMatters",
    "#DeskErgonomics #WorkplaceHealth #PostureMatters",
    "#MindfulMovement #MindBodyConnection #Wellness",
    "#StrengthTraining #FitnessBasics #GetStrong",
    "#CardioWorkout #BusySchedule #FitnessForLife",
    "#NutritionTips #EnergyBoost #FuelYourBody",
    "#SleepRecovery #RestMatters #RecoveryTime",
    "#StressRelief #MentalHealth #ExerciseTherapy",
    "#HomeWorkout #NoGymNeeded #FitnessAtHome",
    "#ProgressTracking #FitnessGoals #StayMotivated",
    "#GoalSetting #SMARTGoals #FitnessJourney",
    "#WorkLifeBalance #HealthyLifestyle #BalanceMatters",
    "#InjuryPrevention #StaySafe #FitnessSafety",
    "#MentalHealth #ExerciseTherapy #Wellness",
    "#FitnessCommunity #SupportSystem #TribeMatters",
    "#SustainableHabits #LongTermSuccess #HealthyHabits",
    "#FitnessTech #AppWorkout #DigitalFitness",
    "#OutdoorFitness #NatureWorkout #FreshAir",
    "#MindBodyConnection #HolisticHealth #Wellness",
    "#ProgressCelebration #MilestoneMoment #FitnessWins",
    "#PlateauBuster #BreakThrough #FitnessProgress",
    "#FitnessMyths #TruthBomb #FitnessFacts",
    "#TimeManagement #BusyLife #FitnessSchedule",
    "#MotivationTips #DisciplineOverMotivation #StayFocused",
    "#LongTermSuccess #FitnessJourney #SustainableResults",
    "#FitnessReflection #JourneyMatters #ProgressCheck"
  ]
};

export const mentalHealthTemplates = {
  topics: [
    "Understanding Anxiety",
    "Mindfulness Basics",
    "Stress Management",
    "Building Resilience",
    "Self-Care Practices",
    "Digital Wellness",
    "Sleep Hygiene",
    "Emotional Intelligence",
    "Setting Boundaries",
    "Gratitude Practice",
    "Social Connection",
    "Creative Expression",
    "Physical Activity for Mental Health",
    "Nutrition and Mood",
    "Breathing Techniques",
    "Journaling for Mental Health",
    "Professional Help",
    "Support Systems",
    "Mindful Technology Use",
    "Nature Therapy",
    "Art Therapy",
    "Music and Mental Health",
    "Laughter Therapy",
    "Volunteering Benefits",
    "Pet Therapy",
    "Meditation Techniques",
    "Cognitive Behavioral Therapy Basics",
    "Emotional Regulation",
    "Building Confidence",
    "Mental Health Advocacy"
  ],
  
  captions: [
    "Anxiety is your body's way of saying something needs attention. Let's understand it better.",
    "Mindfulness isn't about clearing your mind—it's about being present. Start simple.",
    "Stress is inevitable, but how you manage it makes all the difference.",
    "Resilience is a skill you can build. Every challenge makes you stronger.",
    "Self-care isn't selfish—it's essential. You can't pour from an empty cup.",
    "Your relationship with technology affects your mental health. Time to set boundaries.",
    "Quality sleep is the foundation of good mental health. Prioritize it.",
    "Understanding your emotions is the first step to managing them effectively.",
    "Healthy boundaries protect your mental health. Learn to say no.",
    "Gratitude shifts your perspective. What are you thankful for today?",
    "Human connection is vital for mental health. Reach out to someone today.",
    "Creative expression is therapeutic. Find your outlet.",
    "Movement releases endorphins—nature's antidepressants.",
    "What you eat affects how you feel. Fuel your brain with good nutrition.",
    "Your breath is always with you. Use it as an anchor in difficult moments.",
    "Writing helps process emotions. Start with just 5 minutes a day.",
    "Seeking help is a sign of strength, not weakness. You're not alone.",
    "Build your support system. We all need people who have our backs.",
    "Technology should serve you, not control you. Mindful usage matters.",
    "Nature has healing powers. Spend time outdoors regularly.",
    "Art therapy isn't about talent—it's about expression. Try it.",
    "Music can change your mood instantly. Create your mental health playlist.",
    "Laughter really is the best medicine. Find reasons to smile daily.",
    "Helping others helps you. The benefits of volunteering are real.",
    "Pets provide unconditional love and support. Consider animal therapy.",
    "Meditation is a practice, not perfection. Start where you are.",
    "CBT techniques can change your thought patterns. Learn the basics.",
    "Emotional regulation is a skill. Practice makes progress.",
    "Confidence comes from action. Start small, build momentum.",
    "Mental health advocacy starts with you. Share your story, reduce stigma."
  ],
  
  hashtags: [
    "#MentalHealth #AnxietyAwareness #MentalWellness",
    "#Mindfulness #PresentMoment #MentalHealth",
    "#StressManagement #MentalHealth #Wellness",
    "#Resilience #MentalStrength #GrowthMindset",
    "#SelfCare #MentalHealth #Wellness",
    "#DigitalWellness #TechBalance #MentalHealth",
    "#SleepHygiene #MentalHealth #RestMatters",
    "#EmotionalIntelligence #MentalHealth #SelfAwareness",
    "#HealthyBoundaries #MentalHealth #SelfCare",
    "#Gratitude #MentalHealth #PositiveMindset",
    "#SocialConnection #MentalHealth #Community",
    "#CreativeExpression #ArtTherapy #MentalHealth",
    "#PhysicalActivity #MentalHealth #ExerciseTherapy",
    "#Nutrition #MentalHealth #MoodFood",
    "#BreathingTechniques #MentalHealth #CalmMind",
    "#Journaling #MentalHealth #SelfReflection",
    "#ProfessionalHelp #MentalHealth #Therapy",
    "#SupportSystem #MentalHealth #Community",
    "#MindfulTech #DigitalWellness #MentalHealth",
    "#NatureTherapy #MentalHealth #OutdoorHealing",
    "#ArtTherapy #CreativeHealing #MentalHealth",
    "#MusicTherapy #MentalHealth #HealingSounds",
    "#LaughterTherapy #MentalHealth #JoyMatters",
    "#Volunteering #MentalHealth #HelpingOthers",
    "#PetTherapy #MentalHealth #AnimalHealing",
    "#Meditation #MentalHealth #Mindfulness",
    "#CBT #MentalHealth #TherapyTechniques",
    "#EmotionalRegulation #MentalHealth #SelfControl",
    "#Confidence #MentalHealth #SelfEsteem",
    "#MentalHealthAdvocacy #EndStigma #MentalHealth"
  ]
};

export const businessTemplates = {
  topics: [
    "Goal Setting for Success",
    "Time Management Strategies",
    "Building Professional Relationships",
    "Effective Communication",
    "Leadership Development",
    "Problem-Solving Skills",
    "Innovation and Creativity",
    "Financial Planning",
    "Work-Life Balance",
    "Continuous Learning",
    "Networking Strategies",
    "Personal Branding",
    "Stress Management at Work",
    "Decision Making",
    "Team Collaboration",
    "Conflict Resolution",
    "Career Development",
    "Productivity Hacks",
    "Digital Skills",
    "Emotional Intelligence at Work",
    "Strategic Thinking",
    "Risk Management",
    "Customer Service Excellence",
    "Sales Techniques",
    "Project Management",
    "Quality Control",
    "Market Analysis",
    "Competitive Advantage",
    "Sustainable Business Practices",
    "Future-Proofing Your Career"
  ],
  
  captions: [
    "Success starts with clear goals. What do you want to achieve this year?",
    "Time is your most valuable asset. Learn to manage it effectively.",
    "Your network is your net worth. Build meaningful professional relationships.",
    "Communication is the key to success. Master both speaking and listening.",
    "Leadership isn't about title—it's about influence. Develop your skills.",
    "Problems are opportunities in disguise. Sharpen your problem-solving skills.",
    "Innovation drives growth. Think outside the box and embrace creativity.",
    "Financial literacy is essential for business success. Plan your future.",
    "Balance isn't about equal time—it's about equal satisfaction.",
    "Learning never stops. Invest in your continuous development.",
    "Networking is about giving, not just taking. Build genuine connections.",
    "Your personal brand is your reputation. Manage it intentionally.",
    "Work stress is real. Learn healthy coping mechanisms.",
    "Good decisions come from experience. Experience comes from bad decisions.",
    "Collaboration multiplies success. Build strong teams.",
    "Conflict is inevitable. Learn to resolve it constructively.",
    "Your career is a journey, not a destination. Plan your path.",
    "Productivity is about working smarter, not harder. Find your hacks.",
    "Digital skills are non-negotiable. Stay current with technology.",
    "EQ matters more than IQ in the workplace. Develop emotional intelligence.",
    "Think strategically. See the big picture and plan accordingly.",
    "Risk is part of business. Learn to manage it effectively.",
    "Customer service is everyone's job. Exceed expectations.",
    "Sales is about solving problems. Focus on value, not price.",
    "Project management is about people, not just tasks.",
    "Quality is not an act, it's a habit. Build it into your process.",
    "Understand your market. Knowledge is power in business.",
    "Find your competitive advantage. What makes you unique?",
    "Sustainability is good business. Think long-term impact.",
    "The future belongs to those who prepare for it. Future-proof your career."
  ],
  
  hashtags: [
    "#GoalSetting #BusinessSuccess #ProfessionalGrowth",
    "#TimeManagement #Productivity #BusinessTips",
    "#Networking #ProfessionalRelationships #BusinessGrowth",
    "#Communication #Leadership #BusinessSkills",
    "#Leadership #ProfessionalDevelopment #BusinessGrowth",
    "#ProblemSolving #BusinessSkills #Innovation",
    "#Innovation #Creativity #BusinessGrowth",
    "#FinancialPlanning #BusinessSuccess #MoneyMatters",
    "#WorkLifeBalance #ProfessionalLife #Wellness",
    "#ContinuousLearning #ProfessionalDevelopment #Growth",
    "#Networking #BusinessGrowth #ProfessionalConnections",
    "#PersonalBranding #ProfessionalImage #CareerGrowth",
    "#StressManagement #WorkplaceWellness #MentalHealth",
    "#DecisionMaking #BusinessLeadership #StrategicThinking",
    "#TeamCollaboration #Leadership #BusinessSuccess",
    "#ConflictResolution #Leadership #BusinessSkills",
    "#CareerDevelopment #ProfessionalGrowth #Success",
    "#Productivity #BusinessTips #Efficiency",
    "#DigitalSkills #Technology #BusinessGrowth",
    "#EmotionalIntelligence #Leadership #WorkplaceSkills",
    "#StrategicThinking #BusinessLeadership #Planning",
    "#RiskManagement #BusinessStrategy #Leadership",
    "#CustomerService #BusinessExcellence #ServiceMatters",
    "#SalesTechniques #BusinessGrowth #Revenue",
    "#ProjectManagement #Leadership #BusinessSkills",
    "#QualityControl #BusinessExcellence #Standards",
    "#MarketAnalysis #BusinessStrategy #Research",
    "#CompetitiveAdvantage #BusinessStrategy #Differentiation",
    "#SustainableBusiness #LongTermSuccess #Impact",
    "#FutureProofing #CareerGrowth #Adaptation"
  ]
};

// Template selector based on theme
export function getTemplatesForTheme(theme) {
  const lowerTheme = theme.toLowerCase();
  
  if (lowerTheme.includes('fitness') || lowerTheme.includes('workout') || lowerTheme.includes('exercise')) {
    return fitnessTemplates;
  } else if (lowerTheme.includes('mental') || lowerTheme.includes('health') || lowerTheme.includes('wellness')) {
    return mentalHealthTemplates;
  } else if (lowerTheme.includes('business') || lowerTheme.includes('professional') || lowerTheme.includes('career')) {
    return businessTemplates;
  }
  
  // Default to fitness templates
  return fitnessTemplates;
} 